# Generated by Django 4.2.4 on 2023-10-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_post_submitted_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='who_is_hiring_comment_id',
            field=models.IntegerField(unique=True),
        ),
    ]
