# Generated by Django 4.2.4 on 2023-11-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_post_who_is_hiring_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='max_salary',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='min_salary',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
