# Generated by Django 4.2.4 on 2023-11-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_post_max_salary_post_min_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
