# Generated by Django 4.2.4 on 2023-11-19 15:36

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20231119_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vector',
            field=pgvector.django.VectorField(null=True),
        ),
    ]
