# Generated by Django 4.2.4 on 2023-11-19 14:51

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_post_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vector',
            field=pgvector.django.VectorField(null=True),
        ),
    ]
