# Generated by Django 4.2.4 on 2023-11-19 15:35

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_post_currency'),
    ]

    operations = [
        VectorExtension()
    ]
