# Generated by Django 4.2.4 on 2023-11-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_post_vector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-submitted_datetime',)},
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='jobs_compan_name_2a74f5_idx'),
        ),
        migrations.AddIndex(
            model_name='technology',
            index=models.Index(fields=['name'], name='jobs_techno_name_62fe8f_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['name'], name='jobs_title_name_a1cb71_idx'),
        ),
    ]
