# Generated by Django 4.2.4 on 2023-12-29 16:36

from django.db import migrations
from django.db.models import Count
from django.conf import settings


def migrate_data(apps, schema_editor):
    try:
        Subscriber = apps.get_model('users', 'Subscriber')
    except LookupError:
        # Subscriber model doesn't exist yet, skip migration
        return

    Alert = apps.get_model('jobs', 'Alert')
    Technology = apps.get_model('jobs', 'Technology')

    for subscriber in Subscriber.objects.filter(confirmed=True):
        technology = Technology.objects.annotate(
            post_count=Count("posttechnology")
        ).filter(name__contains=subscriber.technology_selected).order_by("-post_count").first()

        if not technology:
            continue

        technology_id = str(technology.id)

        filter_dict = {
            "technologies": [technology_id]
        }

        Alert.objects.create(
            created=subscriber.created,
            modified=subscriber.modified,
            user=subscriber.owner,
            email=subscriber.email,
            confirmed=subscriber.confirmed,
            unsubscribed=subscriber.unsubscribed,
            filter=filter_dict
        )

def reverse_migration_data(apps, schema_editor):
    Alert = apps.get_model('jobs', 'Alert')
    Alert.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0018_alert'),
    ]

    operations = [
        migrations.RunPython(migrate_data, reverse_code=reverse_migration_data),
    ]
