# Generated by Django 4.2.11 on 2024-04-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_alertemailsend'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original_text',
            field=models.TextField(blank=True),
        ),
    ]
