# Generated by Django 4.2.11 on 2024-04-07 07:12

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_post_original_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vector',
            field=pgvector.django.VectorField(dimensions=1536, null=True),
        ),
    ]
