# Generated by Django 4.2.11 on 2024-04-07 07:12

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_alter_post_vector'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=pgvector.django.HnswIndex(ef_construction=64, fields=['vector'], m=16, name='vector_index', opclasses=['vector_l2_ops']),
        ),
    ]
