# Generated by Django 4.2.11 on 2024-04-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_post_vector_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(default='Hacker News', max_length=200),
        ),
    ]
