# Generated by Django 4.2.11 on 2024-06-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_technologymapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='jobs',
            new_name='titles',
        ),
    ]
