# Generated by Django 4.2.11 on 2024-06-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_rename_jobs_compan_name_2a74f5_idx_index_company_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['submitted_datetime'], name='index_post_submitted_datetime'),
        ),
    ]
