# Generated by Django 4.2.11 on 2024-07-20 13:23

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_post_index_post_submitted_datetime'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=pgvector.django.HnswIndex(ef_construction=64, fields=['vector'], m=16, name='vectors_index_2', opclasses=['vector_cosine_ops']),
        ),
    ]
