# Generated by Django 4.2.20 on 2025-04-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_post_vectors_index_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(choices=[('Hacker News', 'Hacker News')], default='Hacker News', max_length=200),
        ),
    ]
